// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA36Wx6xF49A3PyPXFN940Ne7WpbFucHBE',
    appId: '1:1087690667162:web:c952667c967a595e461b23',
    messagingSenderId: '1087690667162',
    projectId: 'vaahane-c8256',
    authDomain: 'vaahane-c8256.firebaseapp.com',
    storageBucket: 'vaahane-c8256.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgCOH_mqjQEz4c-IwvA8HWbEXn4HasNms',
    appId: '1:1087690667162:android:b0aa6b3c26b02a6a461b23',
    messagingSenderId: '1087690667162',
    projectId: 'vaahane-c8256',
    storageBucket: 'vaahane-c8256.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQpUNvQwxpLDzXnqUjpZoXbCcaVEOFdsE',
    appId: '1:1087690667162:ios:0b0eb35f30292fcd461b23',
    messagingSenderId: '1087690667162',
    projectId: 'vaahane-c8256',
    storageBucket: 'vaahane-c8256.firebasestorage.app',
    iosClientId: '1087690667162-tgudl295t1fttj2q2rrneo6795d7v9vb.apps.googleusercontent.com',
    iosBundleId: 'com.example.vaahane',
  );
}
